version: '3.1'
services:
  stats-server:
    build: stats-server
    image: ewm-stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stats

  stats-db:
    image: postgres:14-alpine
    container_name: ewm-stats-postgre-db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=statsuser
      - POSTGRES_PASSWORD=stats

  ewm-service:
    build: ewm-service
    image: ewm-service-image
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ewm

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-postgre-db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewmuser
      - POSTGRES_PASSWORD=ewm